export const HONG_MART_ACTION_CONST = {
  SET_ADMIN_INFO: 'SET_ADMIN_INFO',
  SET_ADMIN_PRODUCT_INFO: 'SET_ADMIN_PRODUCT_INFO',
  SET_SEARCH_INFO: 'SET_SEARCH_INFO',
  INITIALIZE_SEARCH_INFO: 'INITIALIZE_SEARCH_INFO',

  ADMIN_LOGIN_REQUEST: 'ADMIN_LOGIN_REQUEST',
  ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
  ADMIN_LOGIN_FAILURE: 'ADMIN_LOGIN_FAILURE',

  CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
  CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
  CREATE_PRODUCT_FAILURE: 'CREATE_PRODUCT_FAILURE',

  READ_PRODUCT_REQUEST: 'READ_PRODUCT_REQUEST',
  READ_PRODUCT_SUCCESS: 'READ_PRODUCT_SUCCESS',
  READ_PRODUCT_FAILURE: 'READ_PRODUCT_FAILURE',
  READ_SET_VALUE_FOR_UPDATE_AND_DELETE: 'READ_SET_VALUE_FOR_UPDATE_AND_DELETE',

  UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',

  DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',

  INITIALIZE_PRODUCT_COUNT: 'INITIALIZE_PRODUCT_COUNT',
  INCREASE_PRODUCT_COUNT: 'INCREASE_PRODUCT_COUNT',
  DECREASE_PRODUCT_COUNT: 'DECREASE_PRODUCT_COUNT',

  SET_INITIAL_CART_INFO: 'SET_INITIAL_CART_INFO',
  ADD_CART_INFO: 'ADD_CART_INFO',
  DELETE_ALL_CART: 'DELETE_ALL_CART',
  DELETE_ONE_CART: 'DELETE_ONE_CART',
};