export const INPUT_TYPE = {
  GENERAL_INPUT: 'GENERAL_INPUT',
  SEARCH_INPUT: 'SEARCH_INPUT'
};

export const SHOP_MENU_LIST = {
  FRUIT: 'fruit',
  GROCERY: 'grocery',
  MEAL: 'meal',
};

export const PRODUCT_DETAIL_TYPE = {
  LIST: 'LIST',
  DETAIL: 'DETAIL',
};

export const CART_DIALOG = {
  DELETE_ALL: 'DELETE_ALL',
  DELETE_ONE: 'DELETE_ONE',
};

export const SESSION_STATUS = {
  LOADING: 'loading',
  UNAUTHENTICATED: 'unauthenticated',
  AUTHENTICATED: 'authenticated',

  LOADING_RESULT: 'Checking',
  UNAUTHENTICATED_RESULT: 'Sign In',
  AUTHENTICATED_RESULT: 'Sign Out',
};

export const RESPONSIVE_CONST = {
  MOBILE: 'MOBILE',
  TABLET: 'TABLET',
  DESKTOP: 'DESKTOP'
};

export const ADMIN_INFO = {
  ADMIN_USERNAME: 'ADMIN_USERNAME',
  ADMIN_PASSWORD: 'ADMIN_PASSWORD',
};

export const ADMIN_PRODUCT_INFO = {
  // CREATE
  CREATE_PRODUCT_CATEGORY: 'CREATE_PRODUCT_CATEGORY',
  CREATE_PRODUCT_NAME: 'CREATE_PRODUCT_NAME',
  CREATE_PRODUCT_PRICE: 'CREATE_PRODUCT_PRICE',
  CREATE_PRODUCT_PRICE_SALE: 'CREATE_PRODUCT_PRICE_SALE',
  CREATE_PRODUCT_DESCRIPTION: 'CREATE_PRODUCT_DESCRIPTION',

  // READ
  READ_PRODUCT_CATEGORY: 'READ_PRODUCT_CATEGORY',

  // UPDATE
  UPDATE_PRODUCT_ID: 'UPDATE_PRODUCT_ID',
  UPDATE_PRODUCT_CATEGORY: 'UPDATE_PRODUCT_CATEGORY',
  UPDATE_PRODUCT_NAME: 'UPDATE_PRODUCT_NAME',
  UPDATE_PRODUCT_PRICE: 'UPDATE_PRODUCT_PRICE',
  UPDATE_PRODUCT_PRICE_SALE: 'UPDATE_PRODUCT_PRICE_SALE',
  UPDATE_PRODUCT_DESCRIPTION: 'UPDATE_PRODUCT_DESCRIPTION',

  // DELETE
  DELETE_PRODUCT_ID: 'DELETE_PRODUCT_ID',
  DELETE_PRODUCT_CATEGORY: 'DELETE_PRODUCT_CATEGORY',
};

export const SEARCH_INFO = {
  SEARCH_INFO_INPUT: 'SEARCH_INFO_INPUT',
};